using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class EditorSceneMenuGenerator
{
    public const string OutputPath = "Assets/Editor/Generated/SceneMenuItems.cs";
    private static string IncludedScenePathsSOPath = "Assets/Editor/Generated/";
    private static string IncludedScenePathsAssetName = "Included Scene Paths.asset";
    public static string IncludedScenePathFull => Path.Join(IncludedScenePathsSOPath, IncludedScenePathsAssetName);

    public static PathIncluder currentPathIncluder = null;

    /// Setup the Path includer file
    public static void SetupPathIncluder()
    {
        Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
        currentPathIncluder = GetOrCreatePathIncluder();
    }
    
    public static void Generate()
    {
        string[] sceneGuids = AssetDatabase.FindAssets("t:Scene", currentPathIncluder.includedPaths);
        Array.Sort(sceneGuids);
        string sceneListString = string.Join("|", sceneGuids);
        string hash = StableHash(sceneListString);
        
        using (StreamWriter writer = new StreamWriter(OutputPath))
        {
            // Debug.Log($"Creating Hash: // SCENE_HASH:{hash}");
            
            writer.WriteLine($"// This file is auto-generated. DO NOT edit this file.");
            writer.WriteLine($"// SCENE_HASH:{hash}");
            writer.WriteLine();
            writer.WriteLine("using UnityEditor;");
            writer.WriteLine("using UnityEditor.SceneManagement;");
            writer.WriteLine("using UnityEngine;");
            writer.WriteLine();
            writer.WriteLine("public static class SceneMenuItems");
            writer.WriteLine("{");

            foreach (string guid in sceneGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string name = Path.GetFileNameWithoutExtension(path);

                string safeName = name.Replace(" ", "_");

                writer.WriteLine($"    [MenuItem(\"Scenes/{name}\")]");
                writer.WriteLine($"    private static void Load_{safeName}()");
                writer.WriteLine("    {");
                writer.WriteLine($"        OpenScene(\"{path}\");");
                writer.WriteLine("    }");
                writer.WriteLine();
            }

            writer.WriteLine("    private static void OpenScene(string path)");
            writer.WriteLine("    {");
            writer.WriteLine("        if (EditorApplication.isPlaying)");
            writer.WriteLine("            UnityEngine.SceneManagement.SceneManager.LoadScene(path);");
            writer.WriteLine("        else if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())");
            writer.WriteLine("            EditorSceneManager.OpenScene(path);");
            writer.WriteLine("    }");
            writer.WriteLine("}");
        }

        AssetDatabase.Refresh();
    }
    
    public static string StableHash(string input)
    {
        using (var md5 = MD5.Create())
        {
            byte[] bytes = Encoding.UTF8.GetBytes(input);
            byte[] hashBytes = md5.ComputeHash(bytes);
            return BitConverter.ToString(hashBytes).Replace("-", "");
        }
    }

    /// <summary>
    /// Gets or creates the Path Includer for Scene File Paths
    /// Assets/Scenes is a default path for newly created file!
    /// </summary>
    /// <returns></returns>
    private static PathIncluder GetOrCreatePathIncluder()
    {
        // Get existing file. Else create one
        PathIncluder pathIncluder = AssetDatabase.LoadAssetAtPath<PathIncluder>(IncludedScenePathFull);
        
        if (pathIncluder == null)
        {
            pathIncluder = ScriptableObject.CreateInstance<PathIncluder>();
            AssetDatabase.CreateAsset(pathIncluder, IncludedScenePathFull);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        // Set file defaults
        if (pathIncluder.includedPaths.Length == 0)
        {
            pathIncluder.includedPaths = new[]
            {
                "Assets/Scenes"
            };
            EditorUtility.SetDirty(pathIncluder);
            AssetDatabase.SaveAssets();
            Debug.LogWarning($"No included paths set in {IncludedScenePathFull}! Default path 'Assets/Scenes' has been added!");
        }

        return pathIncluder;
    }
}
